const types = {
    TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
    CLEAR_LOGIN_PROPS: 'CLEAR_LOGIN_PROPS',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
  };
  
  export default types;
  