const strings = {
  general: {
    titles: {},
    messages: {},
    errors: {},
  },
  image_text: {
    titles: {},
    alt_text: {
      cart_icon : "cart icon",
      happy_arrow : "Happy Arrow"
    },
    errors: {},
  },
  success_modal: {
    titles: {
      welcome: 'welcome',
      pursue_your_dream_job: 'Pursue your dream job with TradeWorks',
      begin: "let's begin",
    },
    messages: {},
    errors: {},
  },
  join_us: {
    titles: {
      tradeWorks: 'Trade Works',
      firstName: 'First Name',
      lastName: 'Last Name',
      email_address: 'Email Address',
      password: 'Password',
      phone_number: 'Phone Number',
      i_am: "I'm a:",
      company: 'Company',
      individual: 'Individual',
      join: 'JOIN',
      account_exists: "Already have a TradeWorks account?",
      sign_in: 'Sign In',
      sign_up_fr: "By signing up, you agree to TradeWorks",
      terms_services: 'Terms of Service',
      profile_name: 'Profile Name',
      popover_description:
        'This doesn’t have to be your legal name but what you choose to be called in the job market.',
    },
    messages: {
      option_login: 'Optional for faster Log In',
      password_rule: '8 characters. 1 Uppercase letter. 1 number or symbol',
      eight_chars: '8 characters ',          
      one_letter: '1 Uppercase letter ',
      number_symbol: '1 number or symbol',
      success_message: 'Welcome!. Pursue your dream job with TradeWorks.',
    },
    errors: {
      firstName_required: 'First Name is required',
      firstName_min: 'First Name should be at least 3 characters',
      firstName_max: 'First Name cannot be more than 20 characters',
      lastName_required: 'Last Name is required',
      lastName_min: 'Last Name should be at least 3 characters',
      lastName_max: 'Last Name cannot be more than 20 characters',
      email_address_required: 'Email Address is required',
      invalid_email_address: 'Please enter valid email address',
      password_required: 'Password is required',
      password_max: 'Password cannot be more than 20 characters',
      invalid_phone_number: 'Invalid Phone Number'
    },
  },
  login: {
    titles: {
      forgot_your: 'Forgot your',
      password: 'password',
      or: 'or',
      email: 'email',
      not_member: 'Not a member?',
      join_here: 'Join Here',
      email_phone_number: 'Email or Phone Number'
    },
    errors: {
      email_phone_required: 'Email or Phone Number is required',
      invalid_email_phone: 'Please enter valid email or phone number',
    },
  },
  landing_page: {
    titles: {
      log_in: 'Log In',
      join_us: 'JOIN US',
      find_best_candidates: 'FIND THE VERY BEST CANDIDATES',
      architecture_candidates: 'Architecture Candidates',
      interior_design: 'Interior Design Prospects',
      plumbing_heros: 'Plumbing Heros',
      contractor_counsel: "Contractor Counsel",
      welcome: 'WELCOME!',
      connect_with_community: 'CONNECT WITH THE TRADE COMMUNITY',
      get_found: 'GET FOUND',
      job_title: 'JOB TITLE, COMPANY OR KEYWORDS',
      highlight_apprenticeships: 'Highlight Apprenticeships',
      show_skills: 'Show the world your skills',
      find_talent: 'FIND TALENT',
      skills_jobs: 'SKILLS, JOB TITLE OR KEYWORDS',
      appropriate_candidates: 'Ping the most appropiate candidates',
      post_resume: 'Post your resume',
      post_a_job: 'Post a Job',
      footer_text: '2020 ® Tradeworks',
      hiring_companies: 'HIRING COMPANIES',
      architectual_firms: 'Architectual Firms',
      interior_design_firms: 'Interior Design Firms',
      plumbing_outfits: 'Plumbing Outfits',
      pursue_your_dream_job: 'PURSUE YOUR DREAM JOB',
      architecture_positions: 'Architecture Positions',
      interior_design_careers: 'Interior Design Careers',
      plumbing_gigs: 'Plumbing Gigs',
      contractor_openings: 'Contractor Openings',
      placeholder_location: 'city, state, zip',
      feedback_logo_text: 'Beta Testin Feedback Logo',
    },
    messages: {},
    errors: {},
  },
  loggin_header: {
    titles: {
      current_position: 'CURRENT POSITION:',
      welcome: 'WELCOME',
      get_found: 'GET FOUND',
      find_talent: 'FIND TALENT',
      search_jobs: 'SEARCH JOBS',
      my_profile: 'MY PROFILE',
      active_employers: 'ACTIVE EMPLOYERS',
      post_jobs: 'POST JOBS',
      manage_applicants: 'MANAGE APPLICANTS',
      discover_candidates: 'DISCOVER CANDIDATES',
      people: 'People',
      job_title_name_company: 'Job Title, Name, Company',
      city_state_zip: 'City, State or Zip',
      advanced_search: 'Advanced Search',
    },
    messages: {},
    errors: {},
  },
  wizard: {
    titles: {
      completed : "All steps completed",
      Reset : "Reset"
    },
    messages: {},
    errors: {},
  },
  add_trade: {
    titles: {
      thank_you : "THANK YOU FOR JOINING",
      develop : "Let’s develop your professional presence",
      main_trade : "MAIN TRADE",
      what_you_do : "What you ",
      do: ' do',
      what_you_do_remain: ", not where you work.  You may add other trades later",
      location : "YOUR LOCATION",
      currently_reside : "Where you currently reside. City or ZIP code",
      not_usa : "Not USA?",
      student : "ARE YOU A STUDENT?",
      city_zip: "City or ZIP code ",
      Architecture: "Architecture",
    },
    messages: {},
    errors: {},
  },
  add_education : {
    titles: {
      add_education : 'Add Education',
      edu_describe : 'Describe your current or most relevant institution.', 
      add_school : 'You may add other schools later.',
      institution : 'Institution',
      subtitle : "Optional Subtitle",
      city_state : "City/ State",
      from : "From",
      not_usa : "Not USA?",
      expected_graduation : "To (Expected Graduation)",
      program_level : "Program Level",
      degree : "Degree",
      Major : "Major",
      minor : "Minor",
      headline : "Headline",
      make_headline : "Make this my headline",
      highlights : "Highlights and Coursework",
      now_displayed : "Now displayed: Student at Columbia School of Architecture, Planning ... ",
      add_highlight : "Add Highlight",
      add_major : "Add Major",
      candidate: "Candidate, Master’s Degree in Planning",
      select_school: "Select or type your school",
    },
    messages: {},
    errors: {},
  },
  add_exprience:{
    titles:{
      add_exprience: "add Experience",
      add_exprience_des: "What recent experience most closely aligns with your career goals?",
      company: "Company/Entity",
      company_name: "Your Company",
      entity: "Short Description of Entity",
      well_known: "(if not well known)",
      location: "Office Location",
      employment: "Employment Type",
      from: "From",
      month: "Month",
      year: "Year",
      to: "To",
      title: "Title",
      add_title: "Additional Title for this Experience",
      accomplishments: "Accomplishments",
      action: "Start each point with an ACTION verb. ",
      see_List: "See List",
      add_accomplishments: "Add Accomplishment",
      headline: "Headline",
      checkbox: "Make this my Profile Headline",
      headline_des: "Now displayed: Student at Columbia School of Architecture, Planning ... ",
      add_Media: "Add Related Media",
      add_link: "Add Link",
      add_file: "Add File",
      current_postion: "Current Postion?"
    },
    messages: {},
    errors: {},
  },
  add_file: {
    titles: {
     add_link: "ADD LINK",
     add_link_des: "This could be a website or a video link",
     add_link_placeholder_URL: "Type URL address here (yoursite.com)",
     add_another_link: "Add",
     add_link_label: "Link Title",
     add_link_label_placeholder: "This will autofill from site or enter your own title",
     Page_Description: "Page Description",
     textArea_placeholder: "Come from site too.",
     Btn_title: "CAPTURE",
     add_file: "ADD FILE",
     add_file_des: "This could be a jpg, png.",
     step_1: "Step 1 : Find the graphic",
     step_2: "Step 2 : Describe your image",
     step_2_label: "Displayed Caption",
     step_2_placeholder: "The Salas Hacienda - Montañita, Ecuador",
     step_2_textAear: "File Description",
     step_2_textAear_placeholder: "This 10 acres property is located near the coastal town of Montañita, in Ecuador.  The Salas family was very clear about their desire of keeping their new beach recidence in the same local style of open areas, large windows, soft woods and earth tones. ",
     step_3: "Step 3: Optional Link (Choose one)",
     step_3_radio_1: "No Link",
     step_3_radio_2: "URL Address",
     step_3_radio_2_input: "www.SalasHacienda.com",
     step_3_radio_3: "Upload PDF or Doc",
     add_file_btn: "DISPLAY",
    },
    messages: {},
    errors: {},
  },
};

export default strings;
